name: app2-release
on:
  push:
    tags:
      - 'app2-v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Attach assets to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          token: ${{ github.token }}
          artifacts: "app2/app2.sh"
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
